### ISSUE TITLE
Attack animation does not face target

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#110]

**Comment by bjorntore** [comment]
After trying to reproduce it seems this is concerning Attack Random. Face direction is based on current instruction. Will check it out...

**Comment by bjorntore** [comment]
Happens when we run random instructions, for instance: 

```
ApplyInstruction(Utils.Random(new List<string>
            {
                Instructions.AttackMelee,
                Instructions.AttackUp,
                Instructions.AttackDown,
                Instructions.AttackRight,
                Instructions.AttackLeft
            }));
```

Because currentInstructionIndex is used for facing direction, but random instructions don't override the index in any way.
