### ISSUE TITLE
Give feedback when buying robots

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/Robocodo#119]
If you are only buying one robot this would feel better, reduces clicks to get your robot out there. If you want to buy many quickly, it sucks. Maybe Ctrl as modifier key cancels the automatic selection?

Ideas plx!

@Andrioden

**Comment by bjorntore** [comment]
I'm implementing this now. Can be tweaked/removed if it's annoying.

**Comment by Andrioden** [comment]
Hmm. Not feeling it. Seems trival?

**Comment by Andrioden** [comment]
No, but some feedback has to be given. Like a + sign near the garage.
