### ISSUE TITLE
Breakdown of concepts for vision 2.x

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#121]
- Scavengers roams, is humans who roam the planet in vehicles or something. Why? Because they are immune. Are also always hostile. Maybe evil previously military soldiers.
  - Maybe can be captured and used to extract science from.
- Each player is controlling a Society which will grow in size as resources are collected. If too few resources come in the population will go down again. A a high population gives much higher research rate for science (working on cure and developing robot tech). The current needs for resources is indicated in some way and will wary. Will start with only food.
- Population speeds up Science gain.
- Science is used for Technology (tree)
- Energy has to be a resource
- End Goal:
  - Discover a Vaccine: Which is done through Science.
  - Eradicate the virus: Maybe done by cleansing each tile, destroying all infected life, the game has an "bar" which indicate total infection rate.
- Loosing condition:
  - Virus infection rate is to high and the city gets infected. Is the opposite of the mentioned win condition. If the zones near the city has to high infection %, then the bar creeps up by time. If it creeps up to high, to long, you lose.

**Comment by bjorntore** [comment]
Or, if we have a hard time explaining humans surviving at the surface and wanting to kill other humans; could the neutral enemy be rogue robots instead? War bots activated when the world was at its most chaotic, still roaming the surface killing anything that moves?

**Comment by Andrioden** [comment]
Hmm, maybe! But I kinda like the idea of Human Scavangers that is immune to the virus, because then we can later add options to "conduct experiments" on them for +Science.

Also its nice with its own class outside the robot that allows us to write complete custom AI without using the instructions.
