### ISSUE TITLE
Player has technology tree that allows to it unlock TransportRobot

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#127]
The purpose of this task it to create the pattern for technology.
- New class: "TechnologyTree" and "Technology"
- Start with a simple GUI that allows the player to start using science on "Transportation". Can just hardcode it at the start to get tech instantly.
- This unlocks the TransportRobot.
- We need to code review eachother on this.
- Whats synced:
   - The class itself
   - the effect of the tech (thats inherit to the class definition)
   - the tech state

**Comment by bjorntore** [comment]
@Andrioden, should it really be tied to PlayerCityPanel? Shouldn't it be more of a "global" button like in civ? Or are we landing on the fact that there will be only one PlayerCity per player?

**Comment by Andrioden** [comment]
I agree!
