### ISSUE TITLE
New Robot: Purge Robot

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#135]
- Reduces infection on tile.
- Instructions:
  - SEEK NEARBY INFECTION - Goes to a nearby infection tile.
  - PURGE LOCATION - Lowers infection rate

**Comment by bjorntore** [comment]
Maybe SeekNearbyInfectedTile can be a module thingy? If you dont have it you must manually program evey tile to cleanse.

**Comment by Andrioden** [comment]
I would have to disagree. I think it should be part of the standard isntruction-set. Because we shouldnt encourage robot-programming that has to be reprogrammed all the time. Which it has to be if it starts out without a module and require a module to ge the seek.

**Comment by Andrioden** [comment]
Hmm, kinda changed my mind a bit here. This robot is way to easy to use if we allow Seek nearby. Hmm! Not implementing it now for the first version of it. You might be right about making it a module. Hmm, we can discuss it later.
