### ISSUE TITLE
RobotController.RunNextTick with owner != "" - should be replaced with Solar module

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#140]
```
        if (owner != "") //TODO REMOVE AND INSTEAD REPLACE WITH A MODULE ON THE ROBOTS
            energy--;
```

for the Scenario where its used, add modules instead and remove this dirty code.

**Comment by bjorntore** [comment]
What do you mean here? Neutral game objects should have some module giving infinite energy? Solar panel module is not intended to give infinite in the long run, so in that case we need a "NeutralRobotModule" for givning them "superpowers" ?

**Comment by Andrioden** [comment]
Sure, use some other module, but we just have to remember to remove this hardcoded endless energy line.
