### ISSUE TITLE
Should .Serialize() be a interface

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#142]
and should Instructions .Derserialzie() be part of it? Or part of the abstract top class?

**Comment by bjorntore** [comment]
An abstract class can inherit from another abstract class. I think a better solution than an Interface is an abstract class called Sterilizable or something with the required static field and Serialize() function, which all other base classes that need their children to be serializable can inherit from.

**Comment by Andrioden** [comment]
I have given this some thought while rewriting the InstructionsHelper.Deserialize logic to be fully dynamic. And no it should not be an interface used by the Instruction subclasses. The reason is that IsValid and Deserialize for Instruction subclasses has to be static. Which they has to be since they contain logic to derserialize a string which has an unknown Instruction subclass type, meaning every subclass has to be checked if this is the class the string deserializes to.

If Instruction should be an interface for other classes? Maybe. Not considering that for now.

@bjorntore
