### ISSUE TITLE
Wierd animation delay on client when Combat robot hits the side of the map

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#144]
1. Host with build exe
2. Join with client from Unity Engine
3. Make sure the city of the host is at a corner
4. Make it walk into wall and then down or up
5. Notice that animation starts kinda delayed at the client

I thought maybe this had something to do with LastAppliedInstruction beeing delayed, but dont think so since using the following code runs smoothly:

MOVE UP
MOVE UP
MOVE LEFT
IDLE
IDLE
MOVE DOWN
MOVE HOME

**Comment by bjorntore** [comment]
Could it be related to invalid instruction?

**Comment by Andrioden** [comment]
Related to the invalid message when walking into map end then at least, but still its not working as intended. As the animation should start earlier.

**Comment by Andrioden** [comment]
This happens because the variables that affect if the animation should be played (se method ShouldAnimationBePlayed()) is not updated from server to client before the RpcSyncLastAppliedInstruction() call from the server is run.

This is solvable by moving the Animate() method to the update() run on the robot. So the animation always reflect the current state of the robot, meaning we dont need to worry about order of data received.

Please approve of moving Animate() to Update() @bjorntore!

**Comment by bjorntore** [comment]
@Andrioden, as long as you tested it and it works fine I don't mind, I just have a feeling we initially had it there and moved it out because of some issue. Maybe that issue has been resolved by some other change.
