### ISSUE TITLE
Harvest sparks animation does not run on built .exe version of the game

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#147]

**Comment by bjorntore** [comment]
Was not able to reproduce this one today. :/

**Comment by Andrioden** [comment]
We can recreate it together or I look at it myself.

**Comment by bjorntore** [comment]
I tested animation in general, not the harvesting thingy. Did not see you comment before I commented.

**Comment by Andrioden** [comment]
Meaning we reassign it to you?

**Comment by Andrioden** [comment]
It working now, i think i saw that the animation ran in the unity player when the harvester was harvesting WITHOUT being on a node. And then thought it should do so on the build exe file as well. Dunno what happend in my head and why I thought I saw it spark in the unity player. Maybe you fixed it?
