### ISSUE TITLE
Harvester particle effect is delayed

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#160]

**Comment by bjorntore** [comment]
@Andrioden , I looked quickly on this and I was just really confused... Did we change the logic for when anims are played drasticly when you did the major refac?

**Comment by Andrioden** [comment]
@bjorntore: The LastAppliedInstruction variable is correct and updated. You can verify this by putting a Debug.Log("lolol") above the code:

                bodyAnimator.Play("Idle");
                PlayHarvestParticleSystem();

I believe the animation running is bugged. Putting task on your for now.

**Comment by bjorntore** [comment]
I saw that it was set as well. But we did not modify the animations in any way? The particle system isnt even an animation, just an effect triggered from code.

**Comment by Andrioden** [comment]
Hmm, i dont think we did modify it. We can look at it together if you want to.
