### ISSUE TITLE
Client stopping application with play button not leaving game

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#161]
1. Host with exe
2. Join with client
3. Stop application with the |> play button.
4. Notice that the host still has a second city there.

**Comment by bjorntore** [comment]
2.x? This is only a problem if ppl are able to hack the game to do the same as the play button when we release an .exe? IF we ever release an .exe? :P

**Comment by bjorntore** [comment]
@Andrioden

**Comment by Andrioden** [comment]
I commented and closed the wrong issue some days ago.

This is a Unity bug that is solved by downloading the newest Unity (I am using 5.5.0f3).

Read more here if needed: https://forum.unity3d.com/threads/any-way-to-tap-into-ondisconnecterror.431385/
