### ISSUE TITLE
Add music tracks in loop to ingame

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/Robocodo#168]
https://www.assetstore.unity3d.com/en/#!/content/37351

Seems to contain a ton of good tracks. 
I particularly  noticed the "Space"  one for Robocodo. 10$ or something. 

@Andrioden

**Comment by Andrioden** [comment]
Nice quality, go to buying it all! Structured them below:

Ref: https://soundcloud.com/game-music-collection

Normal:
- Ambience (v1.5) - Dark Rumble LOOP (*****)
- Space Demos (v1.5) - Lunar Ambience (*****)
- Ambience (v1.5) - Horror Ambience (****)
- Space Demos (v1.5) - Space Map LOOP (****)
- Space Demos (v1.5) - Deep Space Ambience (***)
- Ambience (v1.5) - Arid Wasteland (***)
- Ambience (v1.5) - Barren Ambience (***)
- Ambience (v1.5) - Desert Ambience  (***) - Confused?

Normal-Intenser
- Space Demos (v1.5) - Station (****) - Maybe menu?

Normal-Happy/Energetic:
- Space Demos (v1.5) - Orbit LOOP (***) - Discovering something?
- Ambience (v1.5) - Frozen Ambience (***)

Combat:
- Space Demos (v1.5) - Hangar Escape LOOP (***) - Sounds like a pokemon battle menu music.

**Comment by bjorntore** [comment]
Purchased!

**Comment by bjorntore** [comment]
Reopening to do an analysis of what songs we want in the game. Look at both Dark Future Music in the project and https://www.assetstore.unity3d.com/en/#!/content/37351.
