### ISSUE TITLE
Animate robot away when entering garage

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#204]
Level 1: Increas transparancy and then at the end of the animation hide the object
Level 2: Flicker transparency, up and down and then finally to fully hidden.
Level 3: Some light/particle effect. Not needed.

**Comment by bjorntore** [comment]
Tweak: b6b8269ea1f971bea87f5c77b35345873db93651

**Comment by bjorntore** [comment]
Think I'll close for now and reopen if you have feedback.
