### ISSUE TITLE
Robot turn rate has to be slower

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#206]
The lights and robot movements is a bit to "edgy", "hard" now. Try to start an game with 20 AI's and youll se.

**Comment by bjorntore** [comment]
Can't get AIs to work now, but tested with a few clients. Plz test urself @Andrioden.

**Comment by Andrioden** [comment]
Oki

**Comment by bjorntore** [comment]
Made the turn quicker. Closing for now. Good enough for scope 2.1 🏅
