### ISSUE TITLE
Autodrop inventory when robot reaches city

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#225]

**Comment by bjorntore** [comment]
Should still stay one tick inside the city, if not the entering/exiting will get fucked.

**Comment by Andrioden** [comment]
I changed my mind because it feels wierd to program this magic behavior. Especially if we has to check that the robot stays at least one tick in the city. Leaving it as it is for now. @bjorntore

**Comment by bjorntore** [comment]
I guess it COULD function a bit like "Reprograming"?    IsEmptyingInventory => do nothing else for one tick. @Andrioden

**Comment by Andrioden** [comment]
It still magic I dont like, compared to for instance dropping it off at another robot. Why should it automatically drop at city for free (no instruction/tick cost) but still cost when dropping at another robot. Naaah, feels bad man!
