### ISSUE TITLE
Show a minor resource effect on robot when carrying resources

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#252]
Has to be designed individually for each robot.

**Comment by Andrioden** [comment]
Just an idea, up to you to determine when/if we should do this @bjorntore. But when I was testing i kinda wanted some visual aid to tell me the robots was carrying resources.

**Comment by bjorntore** [comment]
Some overhead GUI on the robot or some addition to the mesh?

**Comment by Andrioden** [comment]
Addition to the mesh.
