### ISSUE TITLE
Make food more farm-like

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#254]
Same level of detail as copper/iron.

**Comment by bjorntore** [comment]
Tried to make physical straws in blender, but think it will be to demanding performance wise. Might take some inspiration from Civ 6, just with a bit more edges and darker color.

![image](https://user-images.githubusercontent.com/3596256/29969759-e4025ff2-8f21-11e7-8d87-bd9790ed8268.png)

**Comment by Andrioden** [comment]
@bjorntore done? Close Issue? I think its good enough for now.

**Comment by bjorntore** [comment]
Aight, let's create a new issue when we feel like it needs a facelift
