### ISSUE TITLE
Moves screen when pushing arrows in Code Main Loop

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#256]
Under RobotPanel

**Comment by bjorntore** [comment]
Currently the keyboardLock gets activated OnValueChanged on the input field. Since the arrow keys don't submit a value to the field they don't trigger the lock. If you write one letter first and then press an arrow key, the lock is on.

**Comment by bjorntore** [comment]
Maybe we can check every frame if the focused UI game object is the code input field and base the lock on that.

**Comment by Andrioden** [comment]
I tried to find a trigger OnFocus or something, and cant seem to find one we can subscribe to. Also tried OnSelect and OnDeselect. Did not work. Kinda gave up now.

Not a fan of checking every frame. But maybe we should. Nevertheless, changed my mind, gonna close this task and instead move it into #65. Since it would be a waste of code if we dont need to push arrows in the editor.
