### ISSUE TITLE
Robots crash and is destroyed

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#259]
I have been thinking about it. I think your old idea about not allowing stacking will be great. It is way to easy in the beginning. By doing this, we immediately start challenging players on thinking out routes. We also make the transporter and logistics chain much better!

When robots meet, they crash and is destroyed.
- Explosion effect
- Scattered stuff on ground (max 100 allowed globally, not per player) **//Not implemented, might do later**
- Replace with new high performance GameObject
- If you add the same effect for robots taking dmg and getting destroy by other robots, then edit RobotController.TakeDamage NetworkServer.Destroy(gameObject) -> to DestroyWithDelay(this)

Psudocode
1. Server detects crash
2. Server tags robot to be destroyed. No Tick logic will be run for robot in the meanwhile.
3. Client detects crash (for instance by collision, collider overlap), do this in its own script.
4. Client triggers effects
5. Client spawns rubble
6. Client setActive(false) on original robot GameObject
7. Server detects distruction tick and NetworkServer.Destroy robot

**Comment by Andrioden** [comment]
@bjorntore  Robot crash sound is not relative to camera.

**Comment by bjorntore** [comment]
Scattered stuff on ground (max 100 allowed globally, not per player) **//Not implemented, might do later**
