### ISSUE TITLE
Remove automatic looping of Code. Include a LOOP START and LOOP END in demo

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#27]

**Comment by bjorntore** [comment]
@Andrioden, we need to discuss this one before I do anything. :)

**Comment by Andrioden** [comment]
We decided against this, since it would rewards players to not use the main loop, but hardcode an repetetive pattern. They would do this to avoid the instruction tick cost of having to pass the loops. We would make looping instantly, but we want to make looping costly for other than the main loop.
