### ISSUE TITLE
Use crash explosion script to explode on robot health destruction

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#279]
Robots can be destroyed by damage. This should trigger the same explosion.

Suggestion is to rebrand the CollisionHandler to ExplosionTrigger that also detects when robot health is zero. Has to subscribe to some method or we add a Hook to the SyncVar on health. Maybe I should do this if you want to.

RobotController.TakeDamage method should have NetworkServer.Destroy(gameObject) changed to DestroyWithDelay(this).

**Comment by Andrioden** [comment]
Rewrite CollisionHandler

**Comment by bjorntore** [comment]
Closed by bcc1e6fed7054223542dd7c7604a481bb295920e. Using the syncVar DestroyWithDelay and doing a simple if check on that in update.
