### ISSUE TITLE
Remove crashing robots code

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#281]
The problem now is that when you end up with a lot of robots that needs to enter the city to recharge energy, you are gonna get fucked because there is only 4 entry points.

What will you do when you have 10 combat robots and 10 purger robots running around?

Did we think this through enough? The harvesting part is solves yes because players can sovle it with decent logistics networks. But the rest? hmm

**Comment by bjorntore** [comment]
I noticed this when I was testing as well. Got basically impossible. For a
second I was thinking that we had to increase city size quite a bit, but
I'm not sure.

**Comment by bjorntore** [comment]
No matter what, we can keep the explosion effect for robot destruction xD
