### ISSUE TITLE
Loop does not seem to work anymore?

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/Robocodo#288]
In the pic below the robot has actually done about 10 iterations, but it is not incrementing the iteration counter.

**Comment by bjorntore** [comment]
![bug_loop](https://user-images.githubusercontent.com/3596256/31580044-2ad4035a-b145-11e7-9754-e877b35e9400.PNG)

**Comment by Andrioden** [comment]
Note to self. Investigate: How is it synced to client
