### ISSUE TITLE
Create new Network GUI

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#50]
- Se på kildekode til NetworkManager HUD.
- https://bitbucket.org/Unity-Technologies/networking/src/2bdd9961092c4a73443c09694cff5dde9e56f9f1/Runtime/NetworkManagerHUD.cs?at=5.4&fileviewer=file-view-default
- Meaning joining game takes a nickname as input.

**Comment by bjorntore** [comment]
Think we need to create our own network manger hud (GUI) to achieve this, which we have to do at some point anyways. The one included in Unity is for testing only.
