### ISSUE TITLE
When we need to generate with DemoWorldBuilder - Create own custom attribute [IsServerOrDemo]

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/Robocodo#63]
PSODUO:

COPY FUNCIONALITY OF [Server] BUT SKIP IT IF IsDemo.

**Comment by Andrioden** [comment]
Could not figure out how to have the method get called when not debugging. I also could not find any example of that being done. I could not even find a sentence that recommends attributes be used like that. So went with an inline check instead.
