### ISSUE TITLE
Robots should dissapear/reappear when entering/leaving city, and a new "Robots" tab in city

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#66]
A problem we have now is that robots stack ontop of eachother.
- Robots fades in and out when leaving city.
- City panel should have two parts, buy robot, and current robots. which can be selected.
- Selecting a robot in the city panel fades it in.
- Show one icon per robot.

**Comment by bjorntore** [comment]
Closed by 61049c1dfcc112fc2ba60a2c077e8ad9e99a5622 and c9a34c49763ae5833e309cd4d44215dce1f0d549
