### ISSUE TITLE
"Event log text" displaying events that have happend recently

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/Robocodo#75]
We should have some way of telling the player of stuff that happened recently, for instance a scrolling log of recent actions/events in the bottom left corner.

Alternativly we could have small labels pop up over the relevant object.

An example where this would be usefull is when we salvage a robot.
Should say "Robot salvaged for x copper and x iron" or something.
Or if we go with the pop up alternative; "Salvaged!" over the PlayerCity.

**Comment by bjorntore** [comment]
@Andrioden , lemme know what you think bruh

**Comment by Andrioden** [comment]
I really like the idea of popups with a medium-noisy size, that grabs your attention a bit (but not to much noise). That stay there for a bit, like lets stay 1min, but can be clicked on to dismissed instantly.
