### ISSUE TITLE
RobotPanel > CodeRunning part does not scale very well and cuts CodeRunningLabel text.

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#77]

**Comment by Andrioden** [comment]
![robotpanel coderunning textcut](https://cloud.githubusercontent.com/assets/393376/17832744/582ddf46-670a-11e6-8073-76abdb0c9fd8.PNG)

**Comment by bjorntore** [comment]
Isnt that just the label width restricting this?
