### ISSUE TITLE
Why use two level hiarhy for prefabs?

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#78]
- COmbatRobot
  - CombatRObotMesh

Svar foreløpig BT:

PROS:
- Vi kan kaste inn ut ut nye modeller(meshes) uten å måtte rekonfigurere selve game objektet
- Og meshen sine koordinater blir relative til patent game objektet

CONS:
- Complicates how colliders can be used to detect objects on a game business logic.

**Comment by bjorntore** [comment]
Does it really complicate things now that you know you can get the root game object from any child?

**Comment by bjorntore** [comment]
You can have colliders as far down in a hierarchy as you want, the barrel of a tank can have it's own collider where it makes sense to have it. As long as we always keep the logic scripts and interfaces we are looking for on the root game object as this pattern proposes, we will always find what we are looking for at transform.root. The number one advantage is what I mentioned earlier, that we don't have to reconfigure a new game object with all our 10 logic scripts if we decide to replace the model. Pretty sure this is the recommended best practice.

**Comment by Andrioden** [comment]
yea
