### ISSUE TITLE
Reprogramming from resource cost to tick cost

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/Robocodo#90]
Reprogramming should involve "clearing memory", which has a tick cost per instruction. For instance 5 ticks per instruction.

Add tick cost to the button with "50t".

Add "Clearing memory 4/9t ..." with ticking dots to the feedback section.

**Comment by Andrioden** [comment]
Do you agree @bjorntore? If so I will do this pretty soon.

**Comment by bjorntore** [comment]
Maybe you could "Buyout" from the mentioned tick delay for a high fee?

**Comment by Andrioden** [comment]
BT agrees
